title: SungBeomChoi blog # your site title
author: SungBeomChoi
email: choisb3631@neubility.co.kr # email for form submission, you also have to change it in _js/scripts.js
description: 강화학습 + 뉴럴넷을 공부하는 학생입니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sungbeomchoi.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  SUNGBEOMCHOI # replace with your_github_username or comment to remove link from footer

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
lsi: false
excerpt_separator: "\n\n"
incremental: false
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

disqus_url: https://sungbeomchoi-github-io.disqus.com/
disqus:
  shortname: sungbeomchoi-github-io
